import { Checkbox } from "@/components/ui/checkbox";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import type { ModuleDefinition } from "@/types/module";

interface DependencyCheckboxProps {
  module: ModuleDefinition;
  checked: boolean;
  /** Names of dependency modules not yet selected — empty means unblocked. */
  missingDependencies: ModuleDefinition[];
  onToggle: (checked: boolean) => void;
  onResolveDependency: (moduleId: ModuleDefinition["id"]) => void;
}

/**
 * Smart Dependency UI (blueprint section 19): a document whose dependency
 * isn't selected is shown disabled with a clear reason and a one-click fix
 * ("Lengkapi Asesmen") — never generated by silently inventing the missing
 * context.
 */
export function DependencyCheckbox({
  module,
  checked,
  missingDependencies,
  onToggle,
  onResolveDependency,
}: DependencyCheckboxProps) {
  const disabled = missingDependencies.length > 0;

  return (
    <div className="flex items-start gap-3 rounded-md border p-3">
      <Checkbox
        id={module.id}
        checked={checked}
        disabled={disabled}
        onCheckedChange={(state) => onToggle(state === true)}
        className="mt-0.5"
      />
      <div className="flex-1">
        <Label htmlFor={module.id} className="text-sm font-medium">
          {module.name}
        </Label>
        <p className="text-xs text-muted-foreground">{module.description}</p>
        {disabled ? (
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <p className="text-xs text-warning">
              {module.name} — {missingDependencies.map((d) => d.name).join(", ")} belum tersedia.
            </p>
            {missingDependencies.map((dep) => (
              <Button
                key={dep.id}
                type="button"
                size="sm"
                variant="outline"
                onClick={() => onResolveDependency(dep.id)}
              >
                Lengkapi {dep.name}
              </Button>
            ))}
          </div>
        ) : null}
      </div>
    </div>
  );
}
